FROM apache/airflow:2.8.1-python3.10

# Copy DAGs
COPY dags/ /opt/airflow/dags/

# Copy ETL code
COPY etl/ /opt/airflow/etl/

# (Optional) Install requirements if needed
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080
