name: Reddit DAG Full CI/CD with S3

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1  # or whatever region your bucket is in

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install apache-airflow pandas praw boto3 s3fs

    - name: Validate DAG imports
      run: |
        python -c "from reddit_dag import dag; print('✅ DAG imported successfully!')"

    - name: Run ETL Script (Upload to S3)
      run: |
        python reddit_ETL.py
