name: CI/CD → Airflow

on:
  push:
    branches: [ main ]

jobs:
  test-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          # specify a valid version (e.g. 3.10, 3.11, 3.12)
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests & lint
        run: |
          pytest --maxfail=1 --disable-warnings -q
          flake8 .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Airflow image
        run: |
          docker build \
            --file Dockerfile.airflow \
            --tag ${{ secrets.DOCKERHUB_USER }}/airflow:latest .

      - name: Push Airflow image
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/airflow:latest

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AIRFLOW_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add host to known_hosts
        run: |
          ssh-keyscan -H "${{ secrets.AIRFLOW_SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy DAGs via rsync
        run: |
          rsync -avz --delete ./dags/ \
            ${{ secrets.AIRFLOW_SSH_USER }}@${{ secrets.AIRFLOW_SSH_HOST }}:${{ secrets.AIRFLOW_DAG_PATH }}

      - name: Pull new image & restart Docker-Compose
        run: |
          ssh ${{ secrets.AIRFLOW_SSH_USER }}@${{ secrets.AIRFLOW_SSH_HOST }} << 'EOF'
            cd /home/ubuntu/airflow
            docker-compose pull airflow
            docker-compose up -d --no-deps airflow
            docker-compose restart scheduler webserver
          EOF

  integration-test:
    needs: test-build-and-deploy
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12-dind
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install docker-compose
        run: |
          apt-get update && apt-get install -y docker-compose

      - name: Build local Airflow image
        run: docker-compose -f docker-compose.yml build

      - name: Start Airflow stack
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for Airflow health
        run: |
          until curl -sf http://localhost:8080/health; do
            echo "Waiting for Airflow…"
            sleep 5
          done

      - name: Trigger DAG run
        run: |
          docker exec "$(docker-compose ps -q webserver)" \
            airflow dags trigger my_dag_id --run-id ci_test_$(date +%s)

      - name: Wait & assert DAG tasks
        run: |
          CONTAINER=$(docker-compose ps -q webserver)
          for task in $(docker exec $CONTAINER airflow tasks list my_dag_id); do
            docker exec $CONTAINER airflow tasks test my_dag_id $task $(date +%Y-%m-%d)
          done
          pytest tests/integration
