name: Run ETL Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install flake8 pytest

    - name: Set AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: |
        echo "AWS credentials set"
        
    - name: Lint with flake8
      run: |
        flake8 run_ETL.py

    - name: Run tests
      run: |
        pytest

    - name: Run ETL script
      run: |
        python run_ETL.py
